[2024-09-01T11:18:22.403+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Dag_S3.detect_new_or_changed_rows scheduled__2024-08-31T00:00:00+00:00 [queued]>
[2024-09-01T11:18:22.419+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Dag_S3.detect_new_or_changed_rows scheduled__2024-08-31T00:00:00+00:00 [queued]>
[2024-09-01T11:18:22.420+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 9
[2024-09-01T11:18:22.443+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): detect_new_or_changed_rows> on 2024-08-31 00:00:00+00:00
[2024-09-01T11:18:22.450+0000] {standard_task_runner.py:60} INFO - Started process 3850 to run task
[2024-09-01T11:18:22.455+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_Dag_S3', 'detect_new_or_changed_rows', 'scheduled__2024-08-31T00:00:00+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag_s3.py', '--cfg-path', '/tmp/tmptuurft7f']
[2024-09-01T11:18:22.459+0000] {standard_task_runner.py:88} INFO - Job 308: Subtask detect_new_or_changed_rows
[2024-09-01T11:18:22.530+0000] {task_command.py:423} INFO - Running <TaskInstance: ETL_Dag_S3.detect_new_or_changed_rows scheduled__2024-08-31T00:00:00+00:00 [running]> on host 4f7d1346cfdc
[2024-09-01T11:18:22.688+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jasontran' AIRFLOW_CTX_DAG_ID='ETL_Dag_S3' AIRFLOW_CTX_TASK_ID='detect_new_or_changed_rows' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-31T00:00:00+00:00'
[2024-09-01T11:18:22.716+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-09-01T11:18:23.513+0000] {logging_mixin.py:188} INFO - Succesfully read data from AWS S3
[2024-09-01T11:18:23.516+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/includes/emp_dim_insert_update.py", line 25, in detect_new_or_changed_rows
    src_emp_df.drop('employee_status', axis=1, inplace=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 5258, in drop
    return super().drop(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4549, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4591, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6699, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['employee_status'] not found in axis"
[2024-09-01T11:18:23.572+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Dag_S3, task_id=detect_new_or_changed_rows, execution_date=20240831T000000, start_date=20240901T111822, end_date=20240901T111823
[2024-09-01T11:18:23.594+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 308 for task detect_new_or_changed_rows ("['employee_status'] not found in axis"; 3850)
[2024-09-01T11:18:23.632+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-01T11:18:23.680+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
