[2024-08-30T17:39:15.674+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Dag_S3.detect_new_or_changed_rows scheduled__2024-08-30T16:00:00+00:00 [queued]>
[2024-08-30T17:39:15.711+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Dag_S3.detect_new_or_changed_rows scheduled__2024-08-30T16:00:00+00:00 [queued]>
[2024-08-30T17:39:15.713+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 8
[2024-08-30T17:39:15.767+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): detect_new_or_changed_rows> on 2024-08-30 16:00:00+00:00
[2024-08-30T17:39:15.784+0000] {standard_task_runner.py:60} INFO - Started process 262 to run task
[2024-08-30T17:39:15.800+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_Dag_S3', 'detect_new_or_changed_rows', 'scheduled__2024-08-30T16:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag_s3.py', '--cfg-path', '/tmp/tmpyuxvmkwn']
[2024-08-30T17:39:15.817+0000] {standard_task_runner.py:88} INFO - Job 118: Subtask detect_new_or_changed_rows
[2024-08-30T17:39:25.643+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-30T17:39:25.931+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
